### ISSUE TITLE
[dcc32 Error] ceffmx.pas(1109): E2003 Undeclared identifier: 'Platform'

### ISSUE THREAD

**Issue by hlcb91** [CWBudde/DCEF3#1]
I can't compile in RAD Studio XE8.

[dcc32 Fatal Error] DCEF.dpk(40): F2063 Could not compile used unit 'ceffmx.pas'

**Comment by A1Gard** [comment]
change code to this it's working:

procedure TCustomChromiumFMX.MouseWheel(Shift: TShiftState; WheelDelta: Integer;
  var Handled: Boolean);
var
  event: TCefMouseEvent;
  xy : IFMXMouseService ;
begin
  if Browser <> nil then
  with AbsoluteToLocal(xy.GetMousePos ).Round do
  begin
    event.x := X;
    event.y := Y;
    event.modifiers := getModifiers(Shift);
    Browser.Host.SendMouseWheelEvent(@event, 0, WheelDelta);
  end;
end;

**Comment by CWBudde** [comment]
Fixed as suggested.
